# -*- coding: utf-8 -*-
"""Image_Captioning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPt0HsSqw7V4k-256aRqPWv1cNv1qmC-
"""

import torch
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image

class ImageCaptioning:
    def __init__(self):
        #Load a pre-trained CNN model for future extraction
        self.model = models.resnet50(pretrained = True)
        self.model.eval()
        self.transform = transforms.Compose([transforms.Resize((224,224)),transform.ToTensor()])

    def predict(self,image_path):
        image = Image.open(image_path).conver("RGB")
        image = self.transform(image).unsqueeze(0)
        with torch.no_grad():
         features = self.model(image)
        return"Generated Caption(dummy text)"

if __name__ == "_main_":
    captioning = ImageCaptioning()
    print(captioning.predict("image.png"))

